# Copyright 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: Lint Helm Charts

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch to checkout"
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch_name }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: latest
          token: ${{ secrets.GH_OMEC_PAT }}

      - name: Find all Charts and Lint them
        run: |
          for dir in $(find . -maxdepth 1 -mindepth 1 -type d); do
            if [[ -f "$dir/Chart.yaml" ]]; then
              helm lint "$dir"
            fi
          done
