# Copyright 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: Publish Helm Charts

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch to checkout"
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'omec-project'
    env:
      CHARTS_REPO_URL: https://charts.aetherproject.org
      CHARTS_DIR: charts
      REF_CHARTS_DIR: charts-ref
      UMBRELLA_CHARTS: ./sdcore-helm-charts
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch_name }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: latest
          token: ${{ secrets.GH_OMEC_PAT }}

      - name: Get current Index.yaml
        run: |
          rm -rf ${{ env.REF_CHARTS_DIR }} && mkdir -p ${{ env.REF_CHARTS_DIR }}
          curl -o ${{ env.REF_CHARTS_DIR }}/index.yaml ${{ env.CHARTS_REPO_URL }}/index.yaml

      - name: Find all Charts and Package them
        run: |
          rm -rf ${{ env.CHARTS_DIR }} && mkdir -p ${{ env.CHARTS_DIR }}
          for dir in $(find . -maxdepth 1 -mindepth 1 -type d); do
            if [[ -f "$dir/Chart.yaml" ]] && [[ "$dir" != ${{ env.UMBRELLA_CHARTS }} ]]; then
              echo "Packaging charts for: $dir"
              helm dependency update "$dir"
              helm package "$dir" --destination ${{ env.CHARTS_DIR }}
            fi
          done
          helm repo index ${{ env.CHARTS_DIR }} --url ${{ env.CHARTS_REPO_URL }} --merge ${{ env.REF_CHARTS_DIR }}/index.yaml

      - name: Remove not "updated" local Charts (version has not changed)
        working-directory: ${{ env.CHARTS_DIR }}
        run: |
          for file in *.tgz; do
            if grep -q "${{ env.CHARTS_REPO_URL }}/$file" "../${{ env.REF_CHARTS_DIR }}/index.yaml"; then
              echo "Not publishing $file because it is already in ${{ env.CHARTS_REPO_URL }}/index.yaml"
              rm $file
            fi
          done

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avh
          path: ${{ env.CHARTS_DIR }}/
          remote_path: /srv/sites/charts.aetherproject.org/
          remote_host: static.opennetworking.org
          remote_user: ${{ secrets.JENKINS_USERNAME }}
          remote_key: ${{ secrets.JENKINS_SSHKEY }}
          remote_key_pass: ${{ secrets.JENKINS_PASSPHRASE }}

      - name: Get current Index.yaml
        run: |
          rm -rf ${{ env.REF_CHARTS_DIR }} && mkdir -p ${{ env.REF_CHARTS_DIR }}
          curl -o ${{ env.REF_CHARTS_DIR }}/index.yaml ${{ env.CHARTS_REPO_URL }}/index.yaml

      - name: Find all Charts and Package them
        run: |
          rm -rf ${{ env.CHARTS_DIR }} && mkdir -p ${{ env.CHARTS_DIR }}
          echo "Packaging charts for: ${{ env.UMBRELLA_CHARTS }}"
          helm dependency update "${{ env.UMBRELLA_CHARTS }}"
          helm package "${{ env.UMBRELLA_CHARTS }}" --destination ${{ env.CHARTS_DIR }}
          helm repo index ${{ env.CHARTS_DIR }} --url ${{ env.CHARTS_REPO_URL }} --merge ${{ env.REF_CHARTS_DIR }}/index.yaml

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avh
          path: ${{ env.CHARTS_DIR }}/
          remote_path: /srv/sites/charts.aetherproject.org/
          remote_host: static.opennetworking.org
          remote_user: ${{ secrets.JENKINS_USERNAME }}
          remote_key: ${{ secrets.JENKINS_SSHKEY }}
          remote_key_pass: ${{ secrets.JENKINS_PASSPHRASE }}
