# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: Scorecard supply-chain security

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch to checkout"
        required: false
        type: string
        default: ${{ github.ref }}

permissions: read-all

jobs:
  score-analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    if: github.repository_owner == 'omec-project'
    permissions:
      security-events: write
      id-token: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch_name }}
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: Upload to code-scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
