# Copyright 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
name: Validate

on:
  workflow_call:
    inputs:
      branch_name:
        description: "Name of the branch to checkout"
        required: false
        type: string
        default: ${{ github.ref }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch_name }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Build docs
        run: make html

      - name: List built files
        run: |
          files=$(ls ${{ github.workspace }}/_build/html)
          if [ -z "$files" ]; then
            echo "No files found in _build/html directory"
            exit 1
          else
            echo "$files"
          fi
